/**
 * Copyright (c) 2025, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <optional>
#include <string_view>
#include <tuple>

#include "../reflecli_errors.hpp"
#include "../reflecli_concepts.hpp"

namespace reflecli {

namespace intern {

//  Visitor to count the number of option on the current command or subcommand. This Visitor is constexpr compatiple
struct OptionCounterVisitor{
    constexpr void visit(const intern::OptionCompatible auto & value){
        total +=1;
    }

    std::size_t total = 0;
};

/// @brief Return the number of option associated with an argument handler. constexpr
/// @tparam ArgumentsHandler 
/// @param handler 
/// @return number of options 
template<typename ArgumentsHandler>
constexpr std::size_t number_of_options(){
    ArgumentsHandler default_handler{};
    OptionCounterVisitor counter;
    default_handler.introspect(counter);
    return counter.total;
}

struct PositionedOption{
    std::string_view name = "";
    std::size_t position = std::numeric_limits<std::size_t>::max();
};

template<std::size_t N>
using OptionIndex = std::array<PositionedOption, N>;

template<std::size_t N>
struct OptionExtractor{
    constexpr OptionExtractor(OptionIndex<N> & arr) : ref_arr(arr), index(0){}

    constexpr void visit(const intern::OptionCompatible auto & value){
        if constexpr (OptionCompatible<decltype(value)>){
            ref_arr[index] = PositionedOption{ .name = value, .position = index};
            index += 1;
        }
    }

    OptionIndex<N> & ref_arr;
    std::size_t index;
};

template<typename  ArgumentsHandler>
constexpr auto sorted_options_index(ArgumentsHandler & handler) -> OptionIndex<number_of_options<ArgumentsHandler>()>{
    OptionIndex<number_of_options<ArgumentsHandler>()> result{};


    return result;

}




template<typename ArgumentsHandler>
std::optional<ParsingError> recursive_handler_parsing(ArgumentsHandler & handler, int argc, char** argv){
    const auto uargc = static_cast<std::size_t>(argc);

    constexpr std::size_t nargs = number_of_options(handler);
    std::array<std::string_view, nargs> arg_list{};

    for(std::size_t arg = 0; arg < uargc; ++arg){
        std::string_view current_arg(argv[uargc]);
        
    }

    return std::nullopt;
}


} // namespace intern
} // namespace reflecli
