/**
 * Copyright (c) 2025, Adrien Devresse <adev@adev.name>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#pragma once

#include <bitset>
#include <functional>
#include <string_view>
#include <vector>
#include <stdexcept>
#include <optional>

#include "intern/saxcli_impl.hpp"

namespace saxcli {


/// @brief Representation of a compile time string 
/// compatible as a C++20 template parameter 
/// @tparam N size of the literal (including null term)
template<size_t N>
struct StringLiteral {
    /// @brief Construct a StringLiteral from given static text
    /// @param str static text to use
    constexpr StringLiteral(const char (&str)[N]) {
        std::copy_n(str, N, value_);
    }
    
    /// @brief internal buffer
    char value_[N];

    constexpr std::string_view view() const{
        return std::string_view(value_, N-1);
    }
};


/// @brief Option type to use within an CLI option handler struct
/// An Option represent a given CLI option parameter. For instance using 'Option<bool, "verbose">' within the option handler
/// will create an option '--verbose' to the CLI associated with it. The struct member value() will be set to true if the option is present
/// @tparam OptionType 
/// @tparam Name 
/// @tparam Description 
template<typename OptionType, StringLiteral Name, StringLiteral Description = StringLiteral("undocumented")>
struct Option{
    constexpr Option(const OptionType & default_value = OptionType()) : value_(default_value){}

    static_assert(std::is_same_v<OptionType, std::string_view> || std::is_same_v<OptionType, bool>, "Valid option types are 'bool' or 'std::string_view'");

    constexpr OptionType value() const{
        return value_;
    }

    static constexpr std::string_view name(){
        return Name;
    }

    static constexpr std::string_view description(){
        return Description;
    }    

    OptionType value_;

    using is_option_type_= intern::option_type_tag;
};


enum class ParsingErrCode : std::uint8_t{
    invalidOption = 0x01,
    invalidOptionValue = 0x02,
    invalidSubCommand = 0x10,
    corruptedArgv = 0xf0,
};


struct ParsingError{
    ParsingErrCode code;
    std::string message;
};


template<typename ArgumentsHandler>
std::optional<ParsingError> parse_arguments(ArgumentsHandler & handler, int argc, char** argv){

}


} // namespace saxcli
