/**
 * Copyright (c) 2024, Adrien Devresse <adrien.devresse@epfl.ch>
 *
 * Boost Software License - Version 1.0
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include <algorithm>
#include <numeric>
#include <span>

#include <reflecli/reflecli.hpp>

#include <doctest/doctest.h>

namespace reflecli {

namespace tests {

// example of option handler
struct ArgHandlerSimple {

  // declare the introspect function
  template <typename Visitor> constexpr void introspect(Visitor &v) {
    v.visit(space);
    v.visit(name);
  }

  // a boolean option "space"
  Option<bool, "space", "Into space or not"> space;

  // a string view option with a prefix "name"
  Option<std::string_view, "name", "name of the person"> name;
};

struct args_container {
  int argc = 0;
  char **argv = 0;

  std::vector<char *> argv_data;
};

args_container make_argc_argv(std::initializer_list<const char *> arguments) {
  std::vector<char *> argv_data;
  argv_data.reserve(arguments.size() + 1);

  for (const auto &arg : arguments) {
    argv_data.emplace_back(const_cast<char *>(arg));
  }
  argv_data.emplace_back(nullptr);
  return args_container{.argc = static_cast<int>(arguments.size()),
                        .argv = argv_data.data(),
                        .argv_data = std::move(argv_data)};
}

TEST_CASE("option count") {

  ArgHandlerSimple test;

  constexpr auto n_opts = intern::number_of_options<ArgHandlerSimple>();

  CHECK(n_opts == 2);
}

TEST_CASE("basic parsing") {

  auto argv_test = make_argc_argv({"test_prog", "--help"});
}

TEST_CASE("string lit") {

  const char *ref_str = "hello world";

  constexpr auto value = reflecli::StringLiteral{"hello world"};

  CHECK(value.view().size() == std::string_view(ref_str).size());
  CHECK(value.view() == std::string(ref_str));
}

} // namespace tests

} // namespace reflecli
